#!/bin/bash
#
# Research Scheduler - Daily Odoo Knowledge Automation
#
# Purpose: Cron-compatible script for automated research execution
# Schedule: Recommended daily at 2 AM UTC
# Integration: Works with ~/.cline/skills/odoo/deep-research-oca/
#
# Cron setup:
#   0 2 * * * /path/to/research_scheduler.sh >> /var/log/odoo-research.log 2>&1
#

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KNOWLEDGE_DIR="$(dirname "$SCRIPT_DIR")"
NOTES_DIR="$KNOWLEDGE_DIR/notes"
AUTO_RESEARCH_PY="$SCRIPT_DIR/auto_research.py"

# Logging
LOG_FILE="${LOG_FILE:-/tmp/odoo-research-$(date +%Y%m%d).log}"
exec > >(tee -a "$LOG_FILE") 2>&1

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

log_error() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2
}

# Check dependencies
check_dependencies() {
    log "Checking dependencies..."

    if ! command -v python3 &> /dev/null; then
        log_error "python3 not found"
        exit 1
    fi

    # Check Python packages
    python3 -c "import requests" 2>/dev/null || {
        log_error "Python requests package not installed"
        log "Install with: pip3 install requests"
        exit 1
    }

    python3 -c "import yaml" 2>/dev/null || {
        log_error "Python pyyaml package not installed"
        log "Install with: pip3 install pyyaml"
        exit 1
    }

    log "✅ All dependencies satisfied"
}

# Verify GitHub token
check_github_token() {
    if [[ -z "${GITHUB_TOKEN:-}" ]]; then
        log "⚠️  GITHUB_TOKEN not set - API rate limits will be lower (60/hour vs 5000/hour)"
        log "    Set with: export GITHUB_TOKEN=your_token_here"
        return 1
    fi

    log "✅ GitHub token found"
    return 0
}

# Run research for specific domain
run_research_domain() {
    local domain="$1"
    local max_results="${2:-5}"

    log "Running research for domain: $domain (max results: $max_results)"

    python3 "$AUTO_RESEARCH_PY" \
        --domain "$domain" \
        --max-results "$max_results" \
        --output "$NOTES_DIR"

    local exit_code=$?

    if [[ $exit_code -eq 0 ]]; then
        log "✅ Research for $domain completed successfully"
    else
        log_error "Research for $domain failed with exit code: $exit_code"
    fi

    return $exit_code
}

# Rotate research domains daily
get_daily_domain() {
    local day_of_week
    day_of_week=$(date +%u)  # 1-7 (Monday-Sunday)

    case $day_of_week in
        1) echo "module_dev" ;;
        2) echo "docker" ;;
        3) echo "module_dev" ;;
        4) echo "studio" ;;
        5) echo "module_dev" ;;
        6) echo "odoo_sh" ;;
        7) echo "module_dev" ;;
        *) echo "module_dev" ;;
    esac
}

# Generate weekly summary
generate_weekly_summary() {
    local today
    today=$(date +%Y-%m-%d)

    local day_of_week
    day_of_week=$(date +%u)

    # Generate summary on Sundays
    if [[ $day_of_week -ne 7 ]]; then
        return 0
    fi

    log "Generating weekly research summary..."

    local summary_file="$NOTES_DIR/weekly-summary-$today.md"

    cat > "$summary_file" <<EOF
# Weekly Research Summary - $(date +%Y-W%V)

**Generated**: $(date +'%Y-%m-%d %H:%M:%S')

## This Week's Research

EOF

    # Find all notes from this week
    local week_start
    week_start=$(date -v-6d +%Y-%m-%d)  # macOS date command

    find "$NOTES_DIR" -name "????-??-??.md" -type f | while read -r note; do
        note_date=$(basename "$note" .md)

        # String comparison for dates (lexicographic works for YYYY-MM-DD)
        if [[ "$note_date" > "$week_start" || "$note_date" == "$week_start" ]] && [[ "$note_date" < "$today" || "$note_date" == "$today" ]]; then
            echo "### $note_date" >> "$summary_file"
            echo "" >> "$summary_file"

            # Count citations
            citation_count=$(grep -c "^## " "$note" || echo "0")

            echo "- **Citations**: $citation_count" >> "$summary_file"
            echo "- **File**: $note" >> "$summary_file"
            echo "" >> "$summary_file"
        fi
    done

    cat >> "$summary_file" <<EOF

## Next Week's Focus

Based on coverage gaps, prioritize:
- [ ] OCA repository patterns (target: ≥8 citations)
- [ ] Community solutions (target: ≥6 citations)
- [ ] Official documentation (target: ≥6 citations)

---

**Auto-generated by research_scheduler.sh**
EOF

    log "✅ Weekly summary saved to: $summary_file"
}

# Cleanup old logs
cleanup_old_logs() {
    log "Cleaning up old logs..."

    # Keep last 30 days
    find /tmp -name "odoo-research-*.log" -mtime +30 -delete 2>/dev/null || true

    log "✅ Cleanup complete"
}

# Integration check with existing deep-research-oca skill
check_skill_integration() {
    local skill_path="$HOME/.cline/skills/odoo/deep-research-oca/SKILL.md"

    if [[ ! -f "$skill_path" ]]; then
        log "⚠️  Deep-research-oca skill not found at: $skill_path"
        log "    This script works standalone, but skill integration recommended"
        return 1
    fi

    log "✅ Deep-research-oca skill found - integration available"
    return 0
}

# Main execution
main() {
    log "========================================="
    log "Odoo Deep Research Automation"
    log "========================================="

    # Pre-flight checks
    check_dependencies
    check_github_token || true  # Non-fatal
    check_skill_integration || true  # Non-fatal

    # Create notes directory if needed
    mkdir -p "$NOTES_DIR"

    # Get today's research domain (rotating schedule)
    local domain
    domain=$(get_daily_domain)

    log "Today's research domain: $domain"

    # Run research
    if run_research_domain "$domain" 5; then
        log "✅ Daily research completed successfully"
    else
        log_error "Daily research encountered errors"
        exit 1
    fi

    # Weekly summary (Sundays)
    generate_weekly_summary

    # Cleanup
    cleanup_old_logs

    log "========================================="
    log "Research automation complete"
    log "========================================="
}

# Test mode
if [[ "${1:-}" == "--test" ]]; then
    log "Running in test mode..."

    # Override to use test mode
    AUTO_RESEARCH_PY="$AUTO_RESEARCH_PY --test-mode"

    log "Testing auto_research.py..."
    python3 "$SCRIPT_DIR/auto_research.py" --test-mode --domain module_dev --max-results 3

    exit_code=$?

    if [[ $exit_code -eq 0 ]]; then
        log "✅ Test mode successful"
    else
        log_error "Test mode failed with exit code: $exit_code"
    fi

    exit $exit_code
fi

# Run main
main "$@"
