---
# Authoritative Sources for Odoo Agent Expertise
# Last Updated: 2025-11-01
# KB1 Seeded: 26 high-quality citations

official:
  odoo_docs:
    - url: https://www.odoo.com/page/developers-on-demand
      description: Official Odoo development services
      relevance: General Odoo development guidance

    - url: https://www.odoo.com/app/studio-features
      description: Odoo Studio features and capabilities
      relevance: Studio operations (odoo-studio-ops skill)

    - url: https://www.odoo.sh/features
      description: Odoo.sh platform features
      relevance: Odoo.sh lifecycle (odoo-sh-devops skill)

    - url: https://www.odoo.com/documentation/16.0/
      description: Odoo 16.0 official documentation
      relevance: Module development, ORM, views, security

    - url: https://www.odoo.com/documentation/16.0/developer.html
      description: Odoo 16.0 developer guide
      relevance: Complete dev guide with Getting Started tutorial
      quality_score: 100
      added: 2025-11-01

    - url: https://www.odoo.com/documentation/16.0/developer/howtos.html
      description: Odoo 16.0 how-to guides
      relevance: Practical guides for customization, views, web services
      quality_score: 100
      added: 2025-11-01

    - url: https://www.odoo.com/documentation/17.0/
      description: Odoo 17.0 official documentation
      relevance: Version-specific features and migration

    - url: https://www.odoo.com/documentation/17.0/developer/reference/backend/orm.html
      description: Odoo 17.0 ORM API reference
      relevance: Models, Fields, Recordsets, Environment, ORM methods
      quality_score: 100
      added: 2025-11-01

    - url: https://www.odoo.com/documentation/17.0/administration/odoo_sh/getting_started/branches.html
      description: Odoo.sh branches and deployment (17.0)
      relevance: Production, staging, development branch workflows
      quality_score: 100
      added: 2025-11-01

    - url: https://www.odoo.com/documentation/18.0/
description: Odoo 18.0 official documentation
      relevance: Latest version features and patterns
      quality_score: 100
      added: 2025-11-01

    - url: https://www.odoo.com/odoo-18-release-notes
      description: Odoo 18.0 release notes and new features
      relevance: What's new in 18.0 for migration planning
      quality_score: 110
      added: 2025-11-01

    - url: https://www.odoo.com/documentation/19.0/
      description: Odoo 19.0 official documentation
      relevance: Latest features and patterns

    - url: https://www.odoo.com/documentation/19.0/administration/odoo_sh/getting_started/branches.html
      description: Odoo.sh branches (19.0)
      relevance: Latest Odoo.sh deployment and monitoring features
      quality_score: 110
      added: 2025-11-01

    - url: https://www.odoo.com/documentation/14.0/applications/productivity/studio/how_to/export_import.html
      description: Odoo Studio export and import
      relevance: Studio customization export/import workflows
      quality_score: 90
      added: 2025-11-01

oca:
  repositories:
    - url: https://github.com/OCA/account-financial-tools
      description: Accounting and financial modules
      tags: [accounting, finance, invoicing]

    - url: https://github.com/OCA/sale-workflow
      description: Sales workflow enhancements
      tags: [sales, quotations, orders]

    - url: https://github.com/OCA/purchase-workflow
      description: Purchase workflow improvements
      tags: [purchasing, procurement, vendors]

    - url: https://github.com/OCA/stock-logistics-workflow
      description: Inventory and warehouse management
      tags: [inventory, warehouse, logistics]

    - url: https://github.com/OCA/project
      description: Project management modules
      tags: [projects, tasks, timesheets]

    - url: https://github.com/OCA/server-tools
      description: Server tools and utilities
      tags: [performance, utilities, automation]

    - url: https://github.com/OCA/web
      description: Web interface enhancements
      tags: [ui, frontend, widgets]

    - url: https://github.com/OCA/maintainer-tools
      description: OCA development tools
      tags: [pre-commit, linting, scaffolding]
      priority: high
      quality_score: 90
      added: 2025-11-01

    - url: https://github.com/OCA/odoo-pre-commit-hooks
      description: Pre-commit hooks for Odoo (oca-checks-odoo-module)
      tags: [pre-commit, linting, validation]
      priority: high
      quality_score: 90
      added: 2025-11-01

    - url: https://github.com/OCA/maintainer-tools/tree/master/template/module
      description: OCA module template structure
      tags: [template, module-structure, readme]
      quality_score: 90
      added: 2025-11-01

    - url: https://github.com/OCA/multi-company
      description: Multi-company security patterns and modules
      tags: [multi-company, security, record-rules]
      quality_score: 90
      added: 2025-11-01

    - url: https://github.com/OCA/odoo-test-helper
      description: Testing tools and fake model helpers
      tags: [testing, pytest, models]
      quality_score: 90
      added: 2025-11-01

  guidelines:
    - url: https://github.com/OCA/odoo-community.org
      description: OCA community guidelines
      tags: [standards, conventions, licensing]
      priority: high

    - url: https://github.com/OCA/oca-addons-repo-template
      description: OCA repository template
      tags: [scaffolding, ci-cd, structure]
      priority: high
      quality_score: 90
      added: 2025-11-01

    - url: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
      description: OCA contribution guidelines
      tags: [contribution, manifest, versioning, licensing]
      priority: high
      quality_score: 90
      added: 2025-11-01

    - url: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0
      description: Migration guide to Odoo 17.0
      tags: [migration, odoo-17, ruff, linting]
      priority: high
      quality_score: 95
      added: 2025-11-01

communities:
  reddit:
    - url: https://www.reddit.com/r/odoo/
      description: Odoo subreddit
      search_queries:
        - "site:reddit.com/r/odoo ORM performance"
        - "site:reddit.com/r/odoo docker wkhtmltopdf"
        - "site:reddit.com/r/odoo studio export"
        - "site:reddit.com/r/odoo.sh deployment"
      curation_rule: "≥5 upvotes, resolution provided, 2023+"

  forums:
    - url: https://www.odoo.com/forum/help-1
      description: Official Odoo forums
      search_queries:
        - "computed field @api.depends"
        - "record rule multi-company"
        - "migration openupgradelib"
      curation_rule: "Official responses, solved status"

  stackoverflow:
    - url: https://stackoverflow.com/questions/tagged/odoo
      description: Stack Overflow Odoo tag
      search_queries:
        - "[odoo] @api.depends computed field"
        - "[odoo] record rules domain"
        - "[odoo] docker wkhtmltopdf fonts"
      curation_rule: "≥10 upvotes, accepted answer, 2023+"

    - url: https://stackoverflow.com/questions/52309255/odoo-11-improving-performance-of-computed-search-method-when-no-direct-relatio
      description: Computed field performance optimization
      tags: [performance, computed-field, optimization]
      quality_score: 70
      added: 2025-11-01

    - url: https://stackoverflow.com/questions/57477013/many2many-field-related-to-another-model
      description: Many2many relationship patterns
      tags: [many2many, orm, relationships]
      quality_score: 70
      added: 2025-11-01

    - url: https://stackoverflow.com/questions/65776664/odoo-13-record-rules-write-access-on-specific-records
      description: Record rules security best practices
      tags: [security, record-rules, multi-company]
      quality_score: 70
      added: 2025-11-01

    - url: https://stackoverflow.com/questions/31945069/odoo-computed-fields-works-without-store-true-doesnt-work-with-store-true
      description: Computed field store=True behavior
      tags: [computed-field, store, cache]
      quality_score: 70
      added: 2025-11-01

  community_articles:
    - url: https://www.odoo.com/forum/help-1/wkhtml2pdf-in-docker-253393
      description: wkhtmltopdf in Docker configuration
      tags: [docker, wkhtmltopdf, pdf]
      quality_score: 75
      added: 2025-11-01

    - url: https://dev.to/drownie/odoo-docker-fix-print-bug-3phj
      description: Odoo Docker print bug fix
      tags: [docker, wkhtmltopdf, debugging]
      quality_score: 65
      added: 2025-11-01

vendors:
  oca_compliant:
    - url: https://www.odoo-bs.com/odoo-development-services
      description: OCA-compliant Odoo development services
      tags: [consulting, development, support]

  # Add more OCA-aligned vendors as discovered

docker_infrastructure:
  production_deployment:
    - url: https://medium.com/@karan.bk/configure-odoo-with-nginx-as-a-reverse-proxy-9b758056de66
      description: Nginx reverse proxy configuration for Odoo
      tags: [nginx, reverse-proxy, production]
      quality_score: 75
      added: 2025-11-01

    - url: https://github.com/Ozrlz/odoo-nginx-reverse-proxy
      description: Docker nginx reverse proxy with Let's Encrypt
      tags: [docker, nginx, ssl, letsencrypt]
      quality_score: 75
      added: 2025-11-01

    - url: https://jortdevreeze.com/blog/odoo-2/setting-up-a-reverse-proxy-for-odoo-with-nginx-proxy-manager-in-docker-8
      description: Nginx Proxy Manager for Odoo
      tags: [nginx-proxy-manager, docker, gui]
      quality_score: 75
      added: 2025-11-01

    - url: https://victorhachard.github.io/notes/odoo-meet-docker
      description: Comprehensive Docker production deployment guide
      tags: [docker, production, postgresql, logging]
      quality_score: 85
      added: 2025-11-01

testing_tools:
  pytest_odoo:
    - url: https://github.com/camptocamp/pytest-odoo
      description: pytest plugin for Odoo addon testing
      tags: [pytest, testing, tdd]
      quality_score: 80
      added: 2025-11-01

research_targets:
  odoo_module_dev:
    keywords: [orm, models, computed fields, record rules, security, testing, pytest-odoo]
    sources: [oca.repositories, oca.guidelines, communities.stackoverflow]
    priority_repos:
      - OCA/server-tools
      - OCA/maintainer-tools

  odoo_studio_ops:
    keywords: [studio, views, fields, server actions, automations, export]
    sources: [official.odoo_docs, communities.reddit, communities.forums]
    search_focus: "Studio export XML, rollback procedures"

  odoo_sh_devops:
    keywords: [odoo.sh, deployment, branches, builds, staging, logs, backups]
    sources: [official.odoo_docs, communities.reddit]
    search_focus: "Odoo.sh vs self-hosted, Docker parity"

  odoo_docker_claude:
    keywords: [docker, wkhtmltopdf, fonts, anthropic, sdk, non-root]
    sources: [communities.reddit, communities.stackoverflow]
    priority_topics:
      - "Docker multi-stage builds Odoo"
      - "wkhtmltopdf fonts Noto DejaVu"
      - "Anthropic Python SDK Docker"
      - "non-root user pattern"

search_strategies:
  parallel_queries:
    - "Execute all research_targets queries in parallel"
    - "Deduplicate results across sources"
    - "Rank by quality score (upvotes, official response, recency)"

  quality_scoring:
    official_response: 100
    oca_maintainer: 90
    high_upvotes: 80  # ≥20 upvotes
    medium_upvotes: 60  # 10-19 upvotes
    recent_2024: 50
    recent_2023: 30

  recency_bonus:
    2025: +20
    2024: +10
    2023: +5
    2022_older: -10

integration:
  deep_research_skill:
    path: ~/.cline/skills/odoo/deep-research-oca/SKILL.md
    coordination: "Use query sets from this file, output citations to knowledge/notes/"

  daily_workflow:
    - "Run automated research queries (via deep-research-oca skill)"
    - "Review results for quality and relevance"
    - "Add high-signal findings to daily note (knowledge/notes/YYYY-MM-DD.md)"
    - "Update playbooks with validated patterns"
